"use client";

import { useEffect, useState } from "react";
import useSWR from "swr";
import { toast } from "sonner";
import {
  ArrowSquareOut,
  CheckCircle,
  Cloud,
  HardDrives,
  Key,
  Lock,
  Plugs,
  UserCircle,
  Warning,
} from "@phosphor-icons/react/dist/ssr";

import type { ClaudeSettings, OllamaModelsResponse, ProviderTest } from "@/lib/types";

import { proxyFetcher } from "@/lib/proxy-fetcher";

type Mode = ClaudeSettings["mode"];

const MODES: {
  key: Mode;
  label: string;
  blurb: string;
  Icon: typeof Key;
}[] = [
  {
    key: "subscription",
    label: "Claude subscription",
    blurb: "Sign in through the browser. Local development.",
    Icon: UserCircle,
  },
  {
    key: "anthropic_api",
    label: "Anthropic API key",
    blurb: "A key from the Claude Console, billed per token.",
    Icon: Key,
  },
  {
    key: "bedrock",
    label: "Amazon Bedrock",
    blurb: "On Fargate the task role supplies the credentials.",
    Icon: Cloud,
  },
  {
    key: "gateway",
    label: "Gateway / self-hosted",
    blurb: "Any endpoint that speaks the Anthropic Messages API.",
    Icon: Plugs,
  },
  {
    key: "ollama",
    label: "Ollama (local dev)",
    blurb: "Host-installed Ollama — local or :cloud models.",
    Icon: HardDrives,
  },
];

const FIELD_LABELS: Record<string, { label: string; hint?: string; placeholder?: string }> = {
  oauthToken: {
    label: "Subscription token",
    hint: "Generated by `claude setup-token`. Valid for a year.",
    placeholder: "sk-ant-oat…",
  },
  apiKey: { label: "API key", placeholder: "sk-ant-api03-…" },
  authToken: {
    label: "Bearer token",
    hint: "Sent as Authorization: Bearer — not as x-api-key.",
    placeholder: "sk-…",
  },
  bedrockApiKey: {
    label: "Bedrock API key",
    hint: "Optional. Leave empty on Fargate — the task role is used instead.",
    placeholder: "ABSK…",
  },
  baseUrl: { label: "Base URL", placeholder: "http://litellm:4000" },
  awsRegion: { label: "AWS region", placeholder: "us-east-1" },
  model: {
    label: "Model",
    hint: "An alias like `sonnet`, or a full Bedrock inference-profile ID.",
    placeholder: "sonnet",
  },
  smallFastModel: {
    label: "Background model",
    hint: "Optional. Used for session titles and other background work.",
    placeholder: "us.anthropic.claude-haiku-4-5-20251001-v1:0",
  },
};

function fieldMeta(
  mode: Mode,
  key: string,
): { label: string; hint?: string; placeholder?: string } {
  if (mode === "ollama") {
    if (key === "baseUrl") {
      return {
        label: "Ollama base URL",
        placeholder: "http://host.docker.internal:11434",
        hint: "Docker: host.docker.internal:11434. Native dev on the host: http://localhost:11434.",
      };
    }
    if (key === "model") {
      return {
        label: "Model",
        placeholder: "qwen2.5-coder:32b",
        hint: "Local: qwen2.5-coder:32b. Cloud: glm-5:cloud, kimi-k2.5:cloud (requires ollama pull).",
      };
    }
    if (key === "smallFastModel") {
      return {
        label: "Background model",
        placeholder: "gemma4:31b-cloud",
        hint: "Maps to the haiku alias. Sonnet, opus, and subagents use the main model automatically.",
      };
    }
  }
  return FIELD_LABELS[key] ?? { label: key };
}

/**
 * Which Claude Code this installation talks to.
 *
 * Before this screen existed the worker inherited whatever environment its shell
 * had, so authentication was invisible from inside the app. The environment
 * still wins — on Fargate the credentials come from Secrets Manager and must not
 * be editable here — and any field it sets is shown locked rather than silently
 * ignored.
 */
export function ClaudeSettingsClient() {
  const { data, error, mutate, isLoading } = useSWR<ClaudeSettings>(
    "/api/proxy/settings/claude",
    proxyFetcher,
  );

  const [mode, setMode] = useState<Mode>("subscription");
  const [draft, setDraft] = useState<Record<string, string>>({});
  const [saving, setSaving] = useState(false);
  const [testing, setTesting] = useState(false);
  const [result, setResult] = useState<ProviderTest | null>(null);
  const [signIn, setSignIn] = useState<{ session: string; url: string } | null>(null);
  const [code, setCode] = useState("");
  const [ollamaModels, setOllamaModels] = useState<string[]>([]);
  const [loadingModels, setLoadingModels] = useState(false);

  // Re-seed the form whenever the server's view of the mode changes.
  useEffect(() => {
    if (!data) return;
    setMode(data.mode);
    setDraft(
      Object.fromEntries(
        Object.entries(data.fields).map(([key, field]) => [key, field.value ?? ""]),
      ),
    );
  }, [data?.mode, data?.updatedAt]);

  // Switching provider starts from that provider's own stored values, not from
  // whatever was typed for the previous one.
  useEffect(() => {
    if (!data) return;
    const next = data.schema?.[mode];
    if (!next) return;
    setDraft(Object.fromEntries(Object.entries(next).map(([k, f]) => [k, f.value ?? ""])));
    setResult(null);
  }, [mode]);

  // Provider credentials are not an estimator's to read or change, so the API
  // refuses them. Say which it is rather than sitting on "Reading…" for ever.
  if (error) {
    const forbidden = (error as { status?: number }).status === 403;
    return (
      <div className="px-7 py-6">
        <div
          className="rounded-lg px-4 py-3 text-[12.5px]"
          style={{
            background: "var(--app-neg-soft)",
            border: "1px solid var(--app-neg-line)",
            color: "var(--app-neg)",
          }}
        >
          {forbidden
            ? "You do not have permission to configure the provider. Ask whoever administers this installation."
            : `Could not read the configuration: ${(error as Error).message}`}
        </div>
      </div>
    );
  }

  if (isLoading || !data) {
    return (
      <div className="px-7 py-6 text-[13px]" style={{ color: "var(--app-tx-3)" }}>
        Reading the current configuration…
      </div>
    );
  }

  // Not `data.fields`, which only covers the saved mode - picking a provider you
  // have not saved yet would render an empty form with no way to configure it.
  const fields = data.schema?.[mode] ?? (mode === data.mode ? data.fields : {});
  const fieldKeys = Object.keys(fields);

  function payload() {
    const body: Record<string, string> = { mode };
    for (const [key, field] of Object.entries(fields)) {
      if (field.locked) continue;
      const value = draft[key];
      if (value) body[key] = value;
    }
    return body;
  }

  async function save() {
    setSaving(true);
    try {
      const response = await fetch("/api/proxy/settings/claude", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload()),
      });
      const body = await response.json();
      if (!response.ok) {
        toast.error("Could not save that", { description: String(body.detail) });
        return;
      }
      toast.success("Provider saved", {
        description: "The next job will use it — the worker does not need a restart.",
      });
      mutate();
    } finally {
      setSaving(false);
    }
  }

  async function test() {
    setTesting(true);
    setResult(null);
    try {
      const response = await fetch("/api/proxy/settings/claude/test", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload()),
      });
      const body: ProviderTest = await response.json();
      setResult(body);
      if (body.ok) toast.success("Claude Code answered");
      else toast.error("No answer from Claude Code");
    } catch {
      toast.error("Could not reach the API");
    } finally {
      setTesting(false);
    }
  }

  async function refreshOllamaModels() {
    setLoadingModels(true);
    try {
      const params = new URLSearchParams();
      const baseUrl = draft.baseUrl?.trim();
      if (baseUrl) params.set("baseUrl", baseUrl);
      const query = params.toString();
      const response = await fetch(
        `/api/proxy/settings/ollama/models${query ? `?${query}` : ""}`,
      );
      const body: OllamaModelsResponse & { detail?: string } = await response.json();
      if (!response.ok) {
        toast.error("Could not list Ollama models", {
          description: String(body.detail ?? "Is Ollama running on the host?"),
        });
        return;
      }
      const names = body.models.map((entry) => entry.name).filter(Boolean) as string[];
      setOllamaModels(names);
      if (names.length === 0) {
        toast.message("No models found", {
          description: "Pull one on the host: ollama pull qwen2.5-coder:32b",
        });
      } else {
        toast.success(`Found ${names.length} model${names.length === 1 ? "" : "s"}`);
      }
    } catch {
      toast.error("Could not reach the API");
    } finally {
      setLoadingModels(false);
    }
  }

  async function startSignIn() {
    const response = await fetch("/api/proxy/settings/claude/oauth/start", { method: "POST" });
    const body = await response.json();
    if (!response.ok) {
      toast.error("Could not start sign-in", { description: String(body.detail) });
      return;
    }
    setSignIn({ session: body.session, url: body.url });
    window.open(body.url, "_blank", "noopener,noreferrer");
  }

  async function finishSignIn() {
    if (!signIn || !code.trim()) return;
    const response = await fetch("/api/proxy/settings/claude/oauth/code", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ session: signIn.session, code: code.trim() }),
    });
    const body = await response.json();
    if (!response.ok) {
      // A rejected code makes the CLI start a fresh authorization, so the link
      // on screen is already dead. Swap it for the new one rather than leaving
      // the estimator to retry against a challenge that no longer exists.
      const detail = body.detail ?? {};
      const message = typeof detail === "string" ? detail : detail.message;
      if (detail.url) {
        setSignIn({ session: signIn.session, url: detail.url });
        setCode("");
      }
      toast.error(message || "That code was not accepted", { description: detail.hint });
      return;
    }
    toast.success("Signed in to Claude Code");
    setSignIn(null);
    setCode("");
    mutate();
  }

  return (
    <div className="flex flex-col gap-5 px-7 py-6">
      <header className="flex items-baseline justify-between">
        <div>
          <h1 className="text-[19px] font-semibold">Claude Code</h1>
          <p className="mt-1 text-[12.5px]" style={{ color: "var(--app-tx-3)" }}>
            Which model runs the extraction and pricing passes.
            {data.updatedBy ? ` Last changed by ${data.updatedBy}.` : ""}
          </p>
        </div>
        {!data.cliAvailable && (
          <span
            className="flex items-center gap-1.5 rounded-md px-2.5 py-1.5 text-[11.5px]"
            style={{ background: "var(--app-neg-soft)", color: "var(--app-neg)" }}
          >
            <Warning size={13} weight="duotone" />
            The CLI is not installed on the API host
          </span>
        )}
      </header>

      <div className="grid grid-cols-2 gap-2.5 xl:grid-cols-5">
        {MODES.map(({ key, label, blurb, Icon }) => {
          const on = mode === key;
          return (
            <button
              key={key}
              onClick={() => setMode(key)}
              className="flex flex-col items-start gap-1.5 rounded-xl p-3.5 text-left transition"
              style={{
                background: on ? "var(--app-accent-soft)" : "var(--app-panel)",
                border: `1px solid ${on ? "var(--app-accent-line)" : "var(--app-line)"}`,
              }}
            >
              <Icon
                size={17}
                weight="duotone"
                style={{ color: on ? "var(--app-accent)" : "var(--app-tx-3)" }}
              />
              <span
                className="text-[13px] font-semibold"
                style={{ color: on ? "var(--app-accent)" : "var(--app-tx)" }}
              >
                {label}
              </span>
              <span className="text-[11.5px] leading-snug" style={{ color: "var(--app-tx-3)" }}>
                {blurb}
              </span>
            </button>
          );
        })}
      </div>

      {mode === "ollama" && (
        <p
          className="flex items-start gap-2 rounded-lg px-3.5 py-2.5 text-[12px] leading-relaxed"
          style={{ background: "var(--app-warn-soft)", color: "var(--app-warn)" }}
        >
          <Warning size={15} weight="duotone" className="mt-px shrink-0" />
          <span>
            Ollama runs on the host — no Ollama container is bundled. Use a model with 64k+
            context (<code>OLLAMA_CONTEXT_LENGTH=65536</code> before starting Ollama). Phase
            agents declare <code>model: sonnet</code>; in Ollama mode those aliases are routed
            to your configured model automatically. Tool-call fidelity may degrade with
            non-Claude models; check anything these models produce against the drawing.
          </span>
        </p>
      )}

      {mode === "gateway" && (
        <p
          className="flex items-start gap-2 rounded-lg px-3.5 py-2.5 text-[12px] leading-relaxed"
          style={{ background: "var(--app-warn-soft)", color: "var(--app-warn)" }}
        >
          <Warning size={15} weight="duotone" className="mt-px shrink-0" />
          <span>
            A gateway can front Ollama, NVIDIA NIM or OpenRouter — start the bundled one with{" "}
            <code>docker compose --profile oss up -d litellm</code>. Anthropic does not support
            Claude Code against non-Claude models: tool calls are what degrade first, and a loose
            tool call produces an extraction that looks finished and is wrong. Check anything
            these models produce against the drawing.
          </span>
        </p>
      )}

      {mode === "subscription" && data.localDev && (
        <section
          className="rounded-xl p-4"
          style={{ background: "var(--app-panel)", border: "1px solid var(--app-line)" }}
        >
          <h2 className="text-[13px] font-semibold">Sign in through the browser</h2>
          <p className="mt-1 text-[12px]" style={{ color: "var(--app-tx-3)" }}>
            There is no browser inside the container, so Claude Code prints an authorization URL
            and waits for the code it gives you back. Local development only.
          </p>

          {!signIn ? (
            <button
              onClick={startSignIn}
              className="mt-3 flex items-center gap-1.5 rounded-md px-3 py-1.5 text-[12.5px] font-medium"
              style={{ background: "var(--app-accent)", color: "#fff" }}
            >
              <ArrowSquareOut size={13} weight="bold" />
              Sign in to Claude Code
            </button>
          ) : (
            <div className="mt-3 flex flex-col gap-2">
              <a
                href={signIn.url}
                target="_blank"
                rel="noopener noreferrer"
                className="truncate text-[12px] underline"
                style={{ color: "var(--app-accent)" }}
              >
                {signIn.url}
              </a>
              <div className="flex gap-2">
                <input
                  autoFocus
                  value={code}
                  onChange={(event) => setCode(event.target.value)}
                  onKeyDown={(event) => event.key === "Enter" && finishSignIn()}
                  placeholder="Paste the code from the browser"
                  className="flex-1 rounded-md px-2.5 py-1.5 text-[12.5px] outline-none"
                  style={{
                    background: "var(--app-panel-2)",
                    border: "1px solid var(--app-accent-line)",
                    color: "var(--app-tx)",
                  }}
                />
                <button
                  onClick={finishSignIn}
                  className="rounded-md px-3 py-1.5 text-[12.5px] font-medium"
                  style={{ background: "var(--app-accent)", color: "#fff" }}
                >
                  Finish
                </button>
              </div>
            </div>
          )}
        </section>
      )}

      {fieldKeys.length > 0 && (
        <section
          className="flex flex-col gap-3.5 rounded-xl p-4"
          style={{ background: "var(--app-panel)", border: "1px solid var(--app-line)" }}
        >
          {fieldKeys.map((key) => {
            const field = fields[key];
            const meta = fieldMeta(mode, key);
            const showModelPicker = mode === "ollama" && key === "model";
            return (
              <label key={key} className="flex flex-col gap-1">
                <span className="flex items-center gap-1.5 text-[12px] font-medium">
                  {meta.label}
                  <code className="text-[10.5px]" style={{ color: "var(--app-tx-3)" }}>
                    {field.variable}
                  </code>
                  {field.locked && (
                    <span
                      className="flex items-center gap-1 rounded px-1.5 py-px text-[10px]"
                      style={{ background: "var(--app-panel-2)", color: "var(--app-tx-3)" }}
                    >
                      <Lock size={9} weight="bold" />
                      set by environment
                    </span>
                  )}
                </span>
                {showModelPicker && ollamaModels.length > 0 ? (
                  <select
                    value={draft[key] ?? ""}
                    disabled={field.locked}
                    onChange={(event) =>
                      setDraft((current) => ({ ...current, [key]: event.target.value }))
                    }
                    className="rounded-md px-2.5 py-1.5 text-[12.5px] outline-none disabled:opacity-60"
                    style={{
                      background: "var(--app-panel-2)",
                      border: "1px solid var(--app-line)",
                      color: "var(--app-tx)",
                    }}
                  >
                    <option value="">Select a model…</option>
                    {ollamaModels.map((name) => (
                      <option key={name} value={name}>
                        {name}
                      </option>
                    ))}
                  </select>
                ) : (
                  <input
                    value={draft[key] ?? ""}
                    disabled={field.locked}
                    onChange={(event) =>
                      setDraft((current) => ({ ...current, [key]: event.target.value }))
                    }
                    placeholder={meta.placeholder}
                    className="rounded-md px-2.5 py-1.5 text-[12.5px] outline-none disabled:opacity-60"
                    style={{
                      background: "var(--app-panel-2)",
                      border: "1px solid var(--app-line)",
                      color: "var(--app-tx)",
                    }}
                  />
                )}
                {showModelPicker && (
                  <button
                    type="button"
                    onClick={refreshOllamaModels}
                    disabled={loadingModels || field.locked}
                    className="self-start rounded-md px-2.5 py-1 text-[11.5px] disabled:opacity-60"
                    style={{ border: "1px solid var(--app-line)", color: "var(--app-tx-2)" }}
                  >
                    {loadingModels ? "Refreshing…" : "Refresh models from Ollama"}
                  </button>
                )}
                {meta.hint && (
                  <span className="text-[11px]" style={{ color: "var(--app-tx-3)" }}>
                    {meta.hint}
                  </span>
                )}
              </label>
            );
          })}
        </section>
      )}

      <div className="flex items-center gap-2.5">
        <button
          onClick={save}
          disabled={saving}
          className="rounded-md px-3.5 py-1.5 text-[12.5px] font-medium disabled:opacity-60"
          style={{ background: "var(--app-accent)", color: "#fff" }}
        >
          {saving ? "Saving…" : "Save"}
        </button>
        <button
          onClick={test}
          disabled={testing}
          className="rounded-md px-3.5 py-1.5 text-[12.5px] disabled:opacity-60"
          style={{ border: "1px solid var(--app-line)", color: "var(--app-tx-2)" }}
        >
          {testing ? "Asking Claude Code…" : "Test connection"}
        </button>
        <span className="text-[11.5px]" style={{ color: "var(--app-tx-3)" }}>
          Test runs a real one-line pass against what is on screen, not what is saved.
        </span>
      </div>

      {result && (
        <div
          className="flex items-start gap-2 rounded-lg px-3.5 py-2.5 text-[12px]"
          style={{
            background: result.ok ? "var(--app-pos-soft)" : "var(--app-neg-soft)",
            color: result.ok ? "var(--app-pos)" : "var(--app-neg)",
          }}
        >
          {result.ok ? (
            <CheckCircle size={15} weight="duotone" className="mt-px shrink-0" />
          ) : (
            <Warning size={15} weight="duotone" className="mt-px shrink-0" />
          )}
          <span>
            {result.ok ? (
              <>
                Answered through <strong>{result.provider.mode}</strong> on{" "}
                <strong>{result.provider.model}</strong>
                {result.provider.region ? ` in ${result.provider.region}` : ""}.
              </>
            ) : (
              result.error
            )}
          </span>
        </div>
      )}
    </div>
  );
}
